# Generated by Django 5.2.4 on 2025-11-11 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО родителя')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Specialnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название специальности')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Код специальности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('class_of_entry', models.CharField(choices=[('9', '9 класс'), ('11', '11 класс')], max_length=2, verbose_name='Класс поступления')),
                ('hobby', models.CharField(blank=True, max_length=255, verbose_name='Хобби')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('is_guardianship', models.BooleanField(default=False, verbose_name='Опекунство или сирота')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('passport', 'Паспорт'), ('attestat', 'Аттестат'), ('diplom', 'Диплом'), ('med_spravka', 'Медицинская справка'), ('snils', 'СНИЛС'), ('other', 'Другое')], max_length=50, verbose_name='Тип документа')),
                ('available', models.BooleanField(default=False, verbose_name='Доступен')),
                ('scan', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Скан документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание документа')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main_app.abiturient', verbose_name='Абитуриент')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('date_of_conclusion', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения')),
                ('payment_form', models.CharField(choices=[('budget', 'Бюджет'), ('contract', 'Контракт')], default='contract', max_length=10, verbose_name='Форма оплаты')),
                ('maternity_capital', models.BooleanField(default=False, verbose_name='Материнский капитал')),
                ('credit', models.BooleanField(default=False, verbose_name='Кредит')),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogovors', to='main_app.abiturient', verbose_name='Абитуриент')),
                ('roditel_zakazchik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.roditel', verbose_name='Родитель-заказчик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='AbiturientRoditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, max_length=100, verbose_name='Тип родства')),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.abiturient', verbose_name='Абитуриент')),
                ('roditel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.roditel', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Связь абитуриента и родителя',
                'verbose_name_plural': 'Связи абитуриентов и родителей',
                'unique_together': {('abiturient', 'roditel')},
            },
        ),
        migrations.AddField(
            model_name='abiturient',
            name='parents',
            field=models.ManyToManyField(related_name='abiturients', through='main_app.AbiturientRoditel', to='main_app.roditel', verbose_name='Родители'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='specialnost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.specialnost', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Zdorovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseases', models.TextField(blank=True, verbose_name='Заболевания')),
                ('disability', models.BooleanField(default=False, verbose_name='Инвалидность')),
                ('restrictions', models.TextField(blank=True, verbose_name='Ограничения для занятий физкультурой')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('abiturient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='main_app.abiturient', verbose_name='Абитуриент')),
            ],
            options={
                'verbose_name': 'Здоровье',
                'verbose_name_plural': 'Здоровье',
            },
        ),
    ]
