# Generated by Django 6.0 on 2025-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_roditel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('package', 'Полный пакет документов (одним файлом)')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='payment_form',
            field=models.CharField(choices=[('monthly', 'Помесячно'), ('semester', 'По семестрам'), ('yearly', 'За год')], default='contract', max_length=10, verbose_name='Форма оплаты'),
        ),
    ]
