# Generated by Django 5.0 on 2026-04-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_document_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата зачисления'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='status',
            field=models.CharField(choices=[('abiturient', 'Абитуриент'), ('student', 'Студент'), ('graduated', 'Выпускник'), ('expelled', 'Отчислен')], default='abiturient', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='student_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='payment_form',
            field=models.CharField(choices=[('monthly', 'Помесячно'), ('semester', 'По семестрам'), ('yearly', 'За год')], default='monthly', max_length=10, verbose_name='Форма оплаты'),
        ),
    ]
